### ISSUE TITLE
Advancing to Phase 2

### ISSUE THREAD

**Issue by echamudi** [WebAssembly/wat-numeric-values#2]
Hello @binji,

The English [spec text](https://github.com/WebAssembly/wat-numeric-values/blob/master/proposals/wat-numeric-values/Overview.md) of this proposal has been displayed for a while now, and it seems there's no further suggestion or objection in the spec [discussion](https://github.com/WebAssembly/wat-numeric-values/issues/1). Can we advance this proposal to phase two?

> Phase 2 entry requirements:
> - Full proposed English spec text available in a forked repo around which a reasonably high level of consensus exists.
> - Updates to the formal notation, test suite, and reference interpreter are NOT yet required.

And in order to advance, it's mentioned that we need a consensus. Should I schedule a poll in the next CG video call meeting?

Thanks!

**Comment by binji** [comment]
Yes, that sounds like a good plan. Tomorrow's meeting is too soon, but you can add it to the meeting on Nov 24th. Thanks!

**Comment by echamudi** [comment]
(the proposal has been advanced [to phase 2](https://github.com/WebAssembly/proposals/pull/92) 🎉, closing this discussion...)
